"""Add figures table and relationships

Revision ID: 0477afe48dd1
Revises: 576aec1b2d02
Create Date: 2023-08-21 20:00:22.492682

"""
from alembic import op
import sqlalchemy as sa

import iip_search


# revision identifiers, used by Alembic.
revision = "0477afe48dd1"
down_revision = "576aec1b2d02"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "figures",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("locus", sa.Text(), nullable=True),
        sa.Column(
            "searchable_text",
            iip_search.models.TSVector(),
            sa.Computed(
                "\n    to_tsvector('english', coalesce(locus, '') || coalesce(name, ''))\n    ",
            ),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", name="figure_name"),
    )
    op.create_table(
        "figure_inscription",
        sa.Column("figure_id", sa.Integer(), nullable=False),
        sa.Column("inscription_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["figure_id"],
            ["figures.id"],
        ),
        sa.ForeignKeyConstraint(
            ["inscription_id"],
            ["inscriptions.id"],
        ),
        sa.PrimaryKeyConstraint("figure_id", "inscription_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("figure_inscription")
    op.drop_table("figures")
    # ### end Alembic commands ###
