"""Generate slugs from filenames, improve TSVectors

Revision ID: 361861770445
Revises: 0477afe48dd1
Create Date: 2023-08-26 10:34:43.146359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '361861770445'
down_revision = '0477afe48dd1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    op.add_column('inscriptions', sa.Column('slug', sa.String(), server_default="replace(filename, '.xml', '')", nullable=False))
    op.create_unique_constraint("inscriptions_unique_slug", 'inscriptions', ['slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    op.drop_constraint("inscriptions_unique_slug", 'inscriptions', type_='unique')
    op.drop_column('inscriptions', 'slug')
    # ### end Alembic commands ###
