"""Change not_after and not_before to integer columns

Revision ID: 576aec1b2d02
Revises: 81f0c815654a
Create Date: 2023-08-20 20:02:32.829379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "576aec1b2d02"
down_revision = "81f0c815654a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "inscriptions",
        "not_before",
        type_=sa.Integer(),
        postgresql_using="not_before::integer",
    )
    op.alter_column(
        "inscriptions",
        "not_after",
        type_=sa.Integer(),
        postgresql_using="not_before::integer",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "inscriptions",
        "not_before",
        type_=sa.String(),
        postgresql_using="not_before::varchar(255)",
    )
    op.alter_column(
        "inscriptions",
        "not_after",
        type_=sa.String(),
        postgresql_using="not_before::varchar(255)",
    )
    # ### end Alembic commands ###
