"""Add location coordinates and location metadata to inscriptions

Revision ID: 81f0c815654a
Revises: d19279719c0d
Create Date: 2023-08-08 17:04:09.174822

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "81f0c815654a"
down_revision = "d19279719c0d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "inscriptions",
        sa.Column("location_coordinates", postgresql.ARRAY(sa.Float()), nullable=True),
    )
    op.add_column(
        "inscriptions",
        sa.Column(
            "location_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("inscriptions", "location_metadata")
    op.drop_column("inscriptions", "location_coordinates")
    # ### end Alembic commands ###
