"""Add searchable_text generated column to most tables

Revision ID: d19279719c0d
Revises: a3f56715f07f
Create Date: 2023-07-23 12:46:26.369807

"""
from alembic import op
import sqlalchemy as sa

import iip_search


# revision identifiers, used by Alembic.
revision = "d19279719c0d"
down_revision = "a3f56715f07f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bibliographic_entries",
        sa.Column(
            "searchable_text",
            iip_search.models.TSVector(),
            sa.Computed(
                "to_tsvector('english', coalesce('ptr_target', ''))",
            ),
            nullable=True,
        ),
    )
    op.add_column(
        "cities",
        sa.Column(
            "searchable_text",
            iip_search.models.TSVector(),
            sa.Computed(
                "to_tsvector('english', coalesce('placename', '') || coalesce('pleiades_ref', ''))",
            ),
            nullable=True,
        ),
    )
    op.create_unique_constraint(
        "edition_edition_type_inscription_id",
        "editions",
        ["edition_type", "inscription_id"],
    )
    op.add_column(
        "iip_forms",
        sa.Column(
            "searchable_text",
            iip_search.models.TSVector(),
            sa.Computed(
                "to_tsvector('english', coalesce('description', '') || coalesce('ana', ''))",
            ),
            nullable=True,
        ),
    )
    op.add_column(
        "iip_genres",
        sa.Column(
            "searchable_text",
            iip_search.models.TSVector(),
            sa.Computed(
                "to_tsvector('english', coalesce('description', ''))",
            ),
            nullable=True,
        ),
    )
    op.add_column(
        "iip_materials",
        sa.Column(
            "searchable_text",
            iip_search.models.TSVector(),
            sa.Computed(
                "to_tsvector('english', coalesce('description', ''))",
            ),
            nullable=True,
        ),
    )
    op.add_column(
        "iip_preservations",
        sa.Column(
            "searchable_text",
            iip_search.models.TSVector(),
            sa.Computed(
                "to_tsvector('english', coalesce('description', ''))",
            ),
            nullable=True,
        ),
    )
    op.add_column(
        "iip_religions",
        sa.Column(
            "searchable_text",
            iip_search.models.TSVector(),
            sa.Computed(
                "to_tsvector('english', coalesce('description', ''))",
            ),
            nullable=True,
        ),
    )
    op.add_column(
        "iip_writings",
        sa.Column(
            "searchable_text",
            iip_search.models.TSVector(),
            sa.Computed(
                "to_tsvector('english', coalesce('description', '') || coalesce('note', ''))",
            ),
            nullable=True,
        ),
    )
    op.add_column(
        "inscriptions",
        sa.Column(
            "searchable_text",
            iip_search.models.TSVector(),
            sa.Computed(
                "to_tsvector('english', coalesce(description, '') || coalesce(filename, '') || coalesce(short_description, '') || coalesce(title, ''))",
            ),
            nullable=True,
        ),
    )
    op.add_column(
        "languages",
        sa.Column(
            "searchable_text",
            iip_search.models.TSVector(),
            sa.Computed(
                "to_tsvector('english', coalesce('short_form', '') || coalesce('label', ''))",
            ),
            nullable=True,
        ),
    )
    op.add_column(
        "provenances",
        sa.Column(
            "searchable_text",
            iip_search.models.TSVector(),
            sa.Computed(
                "to_tsvector('english', coalesce('placename', ''))",
            ),
            nullable=True,
        ),
    )
    op.add_column(
        "regions",
        sa.Column(
            "searchable_text",
            iip_search.models.TSVector(),
            sa.Computed(
                "to_tsvector('english', coalesce('description', '') || coalesce('label', ''))",
            ),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("regions", "searchable_text")
    op.drop_column("provenances", "searchable_text")
    op.drop_column("languages", "searchable_text")
    op.drop_column("inscriptions", "searchable_text")
    op.drop_column("iip_writings", "searchable_text")
    op.drop_column("iip_religions", "searchable_text")
    op.drop_column("iip_preservations", "searchable_text")
    op.drop_column("iip_materials", "searchable_text")
    op.drop_column("iip_genres", "searchable_text")
    op.drop_column("iip_forms", "searchable_text")
    op.drop_constraint("edition_type_inscription_id", "editions", type_="unique")
    op.drop_column("cities", "searchable_text")
    op.drop_column("bibliographic_entries", "searchable_text")
    # ### end Alembic commands ###
