"""Recompute TSVector columns

Revision ID: e6069030accb
Revises: 361861770445
Create Date: 2023-08-26 10:49:08.762406

"""
from alembic import op
import sqlalchemy as sa

import iip_search


# revision identifiers, used by Alembic.
revision = 'e6069030accb'
down_revision = '361861770445'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # See discussions at 
    # - https://stackoverflow.com/questions/54372666/create-an-immutable-clone-of-concat-ws
    # - https://stackoverflow.com/questions/11005036/does-postgresql-support-accent-insensitive-collations/11007216#11007216
    op.execute(
        """CREATE OR REPLACE FUNCTION immutable_concat_ws(text, VARIADIC text[])
        RETURNS text
        LANGUAGE internal IMMUTABLE PARALLEL SAFE AS
        'text_concat_ws';"""
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bibliographic_entries", "searchable_text")
    op.drop_column("cities", "searchable_text")
    op.drop_column("figures", "searchable_text")
    op.drop_column("iip_forms", "searchable_text")
    op.drop_column("iip_writings", "searchable_text")
    op.drop_column("inscriptions", "searchable_text")
    op.drop_column("languages", "searchable_text")
    op.drop_column("regions", "searchable_text")

    op.add_column(
        "bibliographic_entries",
        sa.Column(
            "searchable_text",
            iip_search.models.TSVector(),
            sa.Computed("to_tsvector('english', immutable_concat_ws(' ', ptr_target, xml_id, raw_xml))"),
            nullable=True,
        ),
    )
    op.add_column(
        "cities",
        sa.Column(
            "searchable_text",
            iip_search.models.TSVector(),
            sa.Computed("to_tsvector('english', immutable_concat_ws(' ', placename, pleiades_ref))"),
            nullable=True,
        ),
    )
    op.add_column(
        "figures",
        sa.Column(
            "searchable_text",
            iip_search.models.TSVector(),
            sa.Computed("to_tsvector('english', immutable_concat_ws(' ', locus, name))"),
            nullable=True,
        ),
    )
    op.add_column(
        "iip_forms",
        sa.Column(
            "searchable_text",
            iip_search.models.TSVector(),
            sa.Computed(
                "to_tsvector('english', immutable_concat_ws(' ', description, ana))",
            ),
            nullable=True,
        ),
    )

    op.add_column(
        "iip_writings",
        sa.Column(
            "searchable_text",
            iip_search.models.TSVector(),
            sa.Computed(
                "to_tsvector('english', immutable_concat_ws(' ', description, note))",
            ),
            nullable=True,
        ),
    )
    op.add_column(
        "inscriptions",
        sa.Column(
            "searchable_text",
            iip_search.models.TSVector(),
            sa.Computed("""
            to_tsvector('english', immutable_concat_ws(' ', description, replace(filename, '.xml', ''), short_description, title))
            """
            ),
            nullable=True,
        ),
    )
    op.add_column(
        "languages",
        sa.Column(
            "searchable_text",
            iip_search.models.TSVector(),
            sa.Computed(
                "to_tsvector('english', immutable_concat_ws(' ', short_form, label))"
            ),
            nullable=True,
        ),
    )
    op.add_column(
        "regions",
        sa.Column(
            "searchable_text",
            iip_search.models.TSVector(),
            sa.Computed(
                "to_tsvector('english', immutable_concat_ws(' ', description, label))",
            ),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
