"""Create trigram index on inscriptions.searchable_text

Revision ID: ffe65da084b7
Revises: 2a61e523bb90
Create Date: 2023-11-12 13:38:10.536077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ffe65da084b7"
down_revision = "2a61e523bb90"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "inscriptions_trigram_idx",
        "inscriptions",
        ["searchable_text"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"description": "gin_trgm_ops"},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "inscriptions_trigram_idx",
        table_name="inscriptions",
        postgresql_using="gin",
        postgresql_ops={"description": "gin_trgm_ops"},
    )
    # ### end Alembic commands ###
